import Head from "next/head";
import Link from "next/link";
import { Link as MuiLink } from "@mui/material";
import Typography from "@mui/material/Typography";
import Toolbar from "@mui/material/Toolbar";
import AppBar from "@mui/material/AppBar";
import CssBaseline from "@mui/material/CssBaseline";
import Theme from "../theme/Theme";
import DarkModeSwitch from "../components/DarkModeSwitch";
import ColorModeContextProvider from "../context/ColorModeContext";
import PopularTopics from "../components/PopularTopics";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PopularTopics />
    </>
  );
}
